version: '2'
volumes:
  openhab-addons:
  openhab-conf:
  openhab-userdata:
  openhab-startup-scripts:
  influxdb:
  grafana:

networks:
  raspberrypi_overlay:

services:
  samba:
    image: dperson/samba:armhf
    ports:
      - "139:139"
      - "445:445"
    networks:
      - raspberrypi_overlay
    volumes:
      - openhab-addons:/mount/openhab-addons
      - openhab-conf:/mount/openhab-conf
      - openhab-startup-scripts:/mount/openhab-startup-scripts
      - openhab-userdata:/mount/openhab-userdata
      - grafana:/mount/grafana
      - influxdb:/mount/influxdb
    restart: unless-stopped
    environment:
      USER: pi;kamLHugö3HZtj4W9Q
      SHARE: raspberry-share;/mount;yes;no;no;all
      USERID: 0
      GROUPID: 0

  traefik:
    image: traefik:latest
    ports:
      - "80:80"
    command: ['--providers.docker', '--providers.docker.endpoint=unix:///var/run/balena.sock', '--entryPoints.web.address=:80', '--providers.docker.exposedbydefault=false', '--providers.docker.network=raspberrypi_overlay']
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    labels:
      io.balena.features.balena-socket: true

  openhab:
    build: ./openhab
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - openhab-addons:/openhab/addons
      - openhab-conf:/openhab/conf
      - openhab-startup-scripts:/etc/cont-init.d
      - openhab-userdata:/openhab/userdata
    labels:
      traefik.backend: openhab
      traefik.docker.network: raspberrypi_overlay
      traefik.enable: true
      traefik.http.middlewares.openhab-auth.basicauth.users: ${USER_OPENHAB_WEB}
      traefik.http.routers.openhab-router.middlewares: openhab-auth
      traefik.http.routers.openhab-router.rule: Host(`raspberrypi`)
      traefik.http.routers.traefik-router.entrypoints: web
      traefik.http.services.openhab-service.loadbalancer.server.port: 8080
    environment:
      OHC_UUID: b727a0c6-c2a3-4932-942f-6b814646f355
      OHC_SECRET: ug3HZtjsfkusj324hfbilo8qrweizfhiuwksjfhniquk2jwhaf

  influxdb:
    image: influxdb:latest
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: openhab
      INFLUXDB_USER: openhab
      INFLUXDB_USER_PASSWORD: sfuodi8isjuosj
      INFLUXDB_LOG_LEVEL: error
      INFLUXDB_DATA_QUERY_LOG_ENABLED: 'true'
      INFLUXDB_REPORTING_DISABLED: 'false'
      INFLUXDB_HTTP_LOG_ENABLED: 'false'
      INFLUXDB_META_LOGGING_ENABLED: 'false'

  grafana:
    image: grafana/grafana:latest
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: kamLHugö3HZtj4W9Q

  watchtower:
    image: containrrr/watchtower
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    labels:
      io.balena.features.balena-socket: true
    environment:
      WATCHTOWER_SCHEDULE: 0 0 4 ? * 6
      WATCHTOWER_CLEANUP: 'true'
      DOCKER_HOST: unix:///var/run/balena.sock

  bluetooth-beacon:
    image: dominikth/rpi-docker-ibeacon:latest
    networks:
      - host
    restart: unless-stopped
    environment:
      UUID: 88BCBF76-F2B4-4BB0-A982-906C16121FF7
      MINOR: 0
      MAJOR: 0
