version: '2'
volumes:
  openhab-addons:
  openhab-conf:
  openhab-userdata:
  openhab-helper-data:

networks:
  smartberry:

services:
  samba:
    build:
      context: ./samba
    ports:
      - 445:445/tcp
    volumes:
      - openhab-conf:/samba/openhab-conf
      - openhab-userdata:/samba/openhab-userdata
      - openhab-helper-data:/samba/openhab-helper-data
    networks:
      - smartberry
    restart: unless-stopped

  openhab:
    build:
      context: ./openhab
    networks:
      - smartberry
    restart: unless-stopped
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - openhab-addons:/openhab/addons
      - openhab-conf:/openhab/conf
      - openhab-userdata:/openhab/userdata
    environment:
      OPENHAB_HOSTKEY:
      OPENHAB_UUID:
      OPENHAB_SECRET:

  openhab-helper:
    build:
      context: ./openhab-helper
    user: node
    networks:
      - smartberry
    restart: unless-stopped
    volumes:
      - openhab-helper-data:/home/node/data/

  bluetooth-beacon:
    image: dominikth/rpi-docker-ibeacon:latest
    network_mode: host
    restart: unless-stopped
    environment:
      UUID: ${BLUETOOTH_BEACON_UUID:-"88BCBF76-F2B4-4BB0-A982-906C16121FF7"}
      MINOR: 0
      MAJOR: 0
