version: '2'
volumes:
  openhab-addons:
  openhab-conf:
  openhab-userdata:
  influxdb:
  grafana:
  swap:

networks:
  raspberrypi_overlay:

services:
  samba:
    build: ./samba
    ports:
      - "139:139"
      - "445:445"
    networks:
      - raspberrypi_overlay
    volumes:
      - openhab-conf:/mount/openhab-conf
      - openhab-userdata:/mount/openhab-userdata
      - grafana:/mount/grafana
      - influxdb:/mount/influxdb
    restart: unless-stopped
    environment:
      AUTH_SAMBA_PASSWORD:
      SHARE: raspberry-share;/mount;yes;no;no;all
      USERID: 0
      GROUPID: 0

  traefik:
    build: ./traefik
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    labels:
      io.balena.features.balena-socket: true
    environment:
      AUTH_OPENHAB_PASSWORD:

  openhab:
    build: ./openhab
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    expose:
      - "8080"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - openhab-addons:/openhab/addons
      - openhab-conf:/openhab/conf
      - openhab-userdata:/openhab/userdata
    environment:
      AUTH_OPENHAB_UUID:
      AUTH_OPENHAB_SECRET:

  influxdb:
    build: ./influxdb
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: openhab
      INFLUXDB_USER: openhab
      AUTH_INFLUXDB_PASSWORD:
      INFLUXDB_LOG_LEVEL: error
      INFLUXDB_DATA_QUERY_LOG_ENABLED: true
      INFLUXDB_REPORTING_DISABLED: false
      INFLUXDB_HTTP_LOG_ENABLED: false
      INFLUXDB_META_LOGGING_ENABLED: false

  grafana:
    build: ./grafana
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: openhab
      AUTH_GRAFANA_PASSWORD:

  watchtower:
    image: containrrr/watchtower
    networks:
      - raspberrypi_overlay
    restart: unless-stopped
    labels:
      io.balena.features.balena-socket: true
    environment:
      WATCHTOWER_SCHEDULE: 0 0 4 ? * 6
      WATCHTOWER_CLEANUP: 'true'
      DOCKER_HOST: unix:///var/run/balena.sock

  bluetooth-beacon:
    image: dominikth/rpi-docker-ibeacon:latest
    network_mode: host
    restart: unless-stopped
    environment:
      UUID: 88BCBF76-F2B4-4BB0-A982-906C16121FF7
      MINOR: 0
      MAJOR: 0

  swap:
    build: ./swap
    restart: unless-stopped
    volumes:
      - swap:/user
    environment:
      SWAP_SIZE: 1024
