version: '2'
volumes:
  openhab-addons:
  openhab-conf:
  openhab-userdata:

networks:
  smartberry:

services:
  samba:
    build:
      context: ./samba
      dockerfile: Dockerfile.template
    ports:
      - "445:445/udp"
      - "139:139/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    networks:
      - smartberry
    volumes:
      - openhab-conf:/mount/conf
      - openhab-userdata:/mount/userdata
    restart: unless-stopped
    environment:
      AUTH_SAMBA_PASSWORD:
      USERID: 9001
      GROUPID: 9001
      SHARE: openhab;/mount;yes;no;no;openhab

  traefik:
    build:
      context: ./traefik
      dockerfile: Dockerfile.template
    ports:
      - 80:80
      - 8080:8080
    networks:
      - smartberry
    restart: unless-stopped
    labels:
      io.balena.features.balena-socket: true

  openhab:
    build:
      context: ./openhab
      dockerfile: Dockerfile.template
    networks:
      - smartberry
    restart: unless-stopped
    expose:
      - 8080
    privileged: true
    volumes:
      - openhab-addons:/openhab/addons
      - openhab-conf:/openhab/conf
      - openhab-userdata:/openhab/userdata
    environment:
      AUTH_OPENHAB_UUID:
      AUTH_OPENHAB_SECRET:
    labels:
      traefik.enable: "true"
      traefik.http.routers.openhab.rule: PathPrefix(`/`)
      traefik.http.routers.openhab.entrypoints: web
      traefik.http.routers.openhab.service: openhab
      traefik.http.services.openhab.loadbalancer.server.port: 8080
      traefik.http.routers.openhab.middlewares: openhab, openhab-auth
      traefik.http.middlewares.openhab.headers.customresponseheaders.Set-Cookie: X-OPENHAB-AUTH-HEADER=true
      traefik.http.middlewares.openhab-auth.basicauth.removeHeader: "true"
      traefik.http.middlewares.openhab-auth.basicauth.users: openhab:${AUTH_OPENHAB_PASSWORD}

  bluetooth-beacon:
    image: dominikth/rpi-docker-ibeacon:latest
    network_mode: host
    restart: unless-stopped
    environment:
      UUID: 88BCBF76-F2B4-4BB0-A982-906C16121FF7
      MINOR: 0
      MAJOR: 0
