version: '2'
volumes:
  openhab-addons:
  openhab-conf:
  openhab-userdata:
  influxdb:
  grafana:

networks:
  smartberry:

services:
  samba:
    build: ./samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    networks:
      - smartberry
    volumes:
      - openhab-conf:/mount/openhab/conf
      - openhab-userdata:/mount/openhab/userdata
      - grafana:/mount/grafana
      - influxdb:/mount/influxdb
    restart: unless-stopped
    environment:
      AUTH_SAMBA_PASSWORD:
      SHARE1: openhab;/mount/openhab;yes;no;no;openhab
      SHARE2: grafana;/mount/grafana;yes;no;no;grafana
      SHARE3: influxdb;/mount/influxdb;yes;no;no;influxdb

  traefik:
    build: ./traefik
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - smartberry
    restart: unless-stopped
    labels:
      io.balena.features.balena-socket: true
    environment:
      AUTH_OPENHAB_PASSWORD:

  openhab:
    build: ./openhab
    networks:
      - smartberry
    restart: unless-stopped
    expose:
      - "8080"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - openhab-addons:/openhab/addons
      - openhab-conf:/openhab/conf
      - openhab-userdata:/openhab/userdata
    environment:
      AUTH_OPENHAB_UUID:
      AUTH_OPENHAB_SECRET:

  influxdb:
    build: ./influxdb
    networks:
      - smartberry
    restart: unless-stopped
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: smartberry
      INFLUXDB_USER: influxdb
      AUTH_INFLUXDB_PASSWORD:
      INFLUXDB_LOG_LEVEL: error
      INFLUXDB_DATA_QUERY_LOG_ENABLED: true
      INFLUXDB_REPORTING_DISABLED: false
      INFLUXDB_HTTP_LOG_ENABLED: false
      INFLUXDB_META_LOGGING_ENABLED: false

  grafana:
    build: ./grafana
    networks:
      - smartberry
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: grafana
      AUTH_GRAFANA_PASSWORD:

  watchtower:
    image: containrrr/watchtower
    networks:
      - smartberry
    restart: unless-stopped
    labels:
      io.balena.features.balena-socket: true
    environment:
      WATCHTOWER_SCHEDULE: 0 0 4 ? * 6
      WATCHTOWER_CLEANUP: 'true'
      DOCKER_HOST: unix:///var/run/balena.sock

  bluetooth-beacon:
    image: dominikth/rpi-docker-ibeacon:latest
    network_mode: host
    restart: unless-stopped
    environment:
      UUID: 88BCBF76-F2B4-4BB0-A982-906C16121FF7
      MINOR: 0
      MAJOR: 0
