version: '2'
volumes:
  openhab-addons:
  openhab-conf:
  openhab-userdata:

networks:
  smartberry:

services:
  samba:
    image: dperson/samba:latest
    ports:
      - 445:445/udp
      - 139:139/udp
      - 139:139/tcp
      - 445:445/tcp
    networks:
      - smartberry
    volumes:
      - openhab-conf:/mount/conf
      - openhab-userdata:/mount/userdata
    restart: unless-stopped
    environment:
      AUTH_SAMBA_PASSWORD:
      USERID: 9001
      GROUPID: 9001
      SHARE: openhab;/mount;yes;no;no;openhab
      USER: openhab;${AUTH_SAMBA_PASSWORD}

  openhab:
    build:
      context: ./openhab
      dockerfile: Dockerfile.template
    networks:
      - smartberry
    restart: unless-stopped
    ports:
      - 80:80
    privileged: true
    volumes:
      - openhab-addons:/openhab/addons
      - openhab-conf:/openhab/conf
      - openhab-userdata:/openhab/userdata
    environment:
      AUTH_OPENHAB_UUID:
      AUTH_OPENHAB_SECRET:
      OPENHAB_HTTP_PORT: 80

  bluetooth-beacon:
    image: dominikth/rpi-docker-ibeacon:latest
    network_mode: host
    restart: unless-stopped
    environment:
      UUID: 88BCBF76-F2B4-4BB0-A982-906C16121FF7
      MINOR: 0
      MAJOR: 0
