version: '2'
volumes:
  openhab-addons:
  openhab-conf:
  openhab-userdata:

networks:
  smartberry:

services:
  samba:
    build:
      context: ./samba
      dockerfile: Dockerfile
    ports:
      - 445:445/tcp
    volumes:
      - ./samba/config.yml:/data/config.yml
      - openhab-conf:/samba/conf
      - openhab-userdata:/samba/userdata
    networks:
      - smartberry
    restart: unless-stopped

  openhab:
    build:
      context: ./openhab
      dockerfile: Dockerfile
    networks:
      - smartberry
    restart: unless-stopped
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - openhab-addons:/openhab/addons
      - openhab-conf:/openhab/conf
      - openhab-userdata:/openhab/userdata
    environment:
      OPENHAB_HOSTKEY:
      OPENHAB_UUID:
      OPENHAB_SECRET:

  bluetooth-beacon:
    image: dominikth/rpi-docker-ibeacon:latest
    network_mode: host
    restart: unless-stopped
    environment:
      UUID: ${BLUETOOTH_BEACON_UUID:-"88BCBF76-F2B4-4BB0-A982-906C16121FF7"}
      MINOR: 0
      MAJOR: 0
