FROM traefik:latest
RUN apk add --update --no-cache openssl
COPY ./pre-traefik.sh /pre-traefik.sh
RUN /bin/bash -c 'chmod +x /pre-traefik.sh'
COPY ./traefik.toml /etc/traefik/traefik.toml
ENTRYPOINT ["/pre-traefik.sh"]
