FROM traefik:latest
COPY ./traefik.toml /etc/traefik/traefik.toml
COPY ./pre-traefik.sh /usr/bin/pre-traefik.sh
RUN /bin/bash -c 'chmod +x /usr/bin/pre-traefik.sh'
ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/pre-traefik.sh"] #TODO
