[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"

[api]
  insecure = true
  dashboard = true

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/balena.sock"
    exposedByDefault = false
    network = "raspberrypi_overlay"

  [providers.file]
    filename = "/etc/traefik/dynamic-conf.toml"
