FROM grafana/grafana:latest
COPY ./pre-grafana.sh /usr/local/bin/pre-grafana.sh
USER root
RUN /bin/bash -c 'chmod +x /usr/local/bin/pre-grafana.sh'
USER grafana
ENTRYPOINT ["/usr/local/bin/pre-grafana.sh"]
