FROM openhab/openhab:latest
#FROM openhab/openhab:latest-alpine

RUN apt-get update && apt-get install \
    rsync \
    curl

# RUN apk add --no-cache \
#     rsync \
#     curl \
#     unzip \
#     grep

COPY --chown=${USER_ID}:${GROUP_ID} ./mounts/etc/cont-init.d/ /etc/cont-init.d
COPY --chown=${USER_ID}:${GROUP_ID} ./mounts/tmp/openhab/ /tmp/${OPENHAB_HOME}

RUN curl -O -L https://github.com/jimtng/openhab-helper-libraries/archive/oh3-patch.zip && unzip oh3-patch.zip && rm oh3-patch.zip && \
    chown -R ${USER_ID}:${GROUP_ID} ./openhab-helper-libraries-oh3-patch && \
    mv ./openhab-helper-libraries-oh3-patch/Core/automation/lib/python/configuration.py.example /tmp/${OPENHAB_HOME}/conf/automation/lib/python/configuration.py && \
    mv ./openhab-helper-libraries-oh3-patch/Core/automation/lib/python/personal/__init__.py.example /tmp/${OPENHAB_HOME}/conf/automation/lib/python/personal/__init__.py && \
    mv ./openhab-helper-libraries-oh3-patch/Core/automation/lib/python/core/ /tmp/${OPENHAB_HOME}/conf/automation/lib/python/ && \
    mv ./openhab-helper-libraries-oh3-patch/Core/automation/jsr223/python/core/ /tmp/${OPENHAB_HOME}/conf/automation/jsr223/python/ && \
    rm -R ./openhab-helper-libraries-oh3-patch
