name: Deploy to balena

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Balena Push
      run: |
        curl -L -o /tmp/balena.zip {{ secrets.BALENA_CLI_RELEASE_ZIP }}
        unzip /tmp/balena.zip -d /opt
        rm /tmp/balena.zip
        export PATH=$PATH:/opt/balena-cli
        balena login --token ${{ secrets.BALENA_API_TOKEN }}
        balena push ${{ secrets.BALENA_APPLICATION_NAME }}
