name: Deploy to balena

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Get contents README.md
      id: readme
      run: |
        content=`cat ./README.md`
        echo "::set-output name=content::$content"
    - name: Markdown to HTML
      uses: lifepal/markdown-to-html@v1.2
      id: markdown
      with: 
        text: ${{ steps.readme.outputs.content }}
    - name: Save HTML
      run: |
        mkdir ./openhab/mounts/tmp/openhab/conf/html
        echo "${{ steps.markdown.outputs.html }}" >> ./openhab/mounts/tmp/openhab/conf/html/index.html
    - name: Push to balena
      run: |
        curl -L -o /tmp/balena.zip ${{ secrets.BALENA_CLI_RELEASE_ZIP }}
        unzip /tmp/balena.zip -d /opt
        rm /tmp/balena.zip
        export PATH=$PATH:/opt/balena-cli
        balena login --token ${{ secrets.BALENA_API_TOKEN }}
        balena push ${{ secrets.BALENA_APPLICATION_NAME }} --detached
